[project]
name = "cottonwood"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
license = { text = "MIT", file = "LICENSE" }
classifiers = [
	"License :: OSI Approved :: MIT License",
]
